UPDATE: hook calling script

diff --git a/hooks/pre-push b/hooks/pre-push
--- a/hooks/pre-push
+++ b/hooks/pre-push
@@ -1,20 +1,28 @@
-echo "Running CheckStyle..."
+#!/bin/sh
 
-./gradlew checkstyleMain
+# This script should be saved in a git repo as a hook file, e.g. .git/hooks/pre-receive.
+# It looks for scripts in the .git/hooks/pre-receive.d directory and executes them in order,
+# passing along stdin. If any script exits with a non-zero status, this script exits.
 
-if [ "$status" = 0 ] ; then
-    echo "No Style Errors :>"
-    exit 0
-else
-    echo 1>&2 "Please format correctly or Lars will be sad :("
-    exit 1
+script_dir=$(dirname $0)
+hook_name=$(basename $0)
+
+hook_dir="$script_dir/$hook_name.d"
+
+if [[ -d $hook_dir ]]; then
+  stdin=$(cat /dev/stdin)
+
+  for hook in $hook_dir/*; do
+    echo "Running $hook_name/$hook hook"
+    echo "$stdin" | $hook "$@"
+
+    exit_code=$?
+
+    if [ $exit_code != 0 ]; then
+      exit $exit_code
+    fi
+  done
 fi
 
-echo "Running Tests..."
-
-./gradlew test
-
-RESULT=$?
-
-exit $RESULT
+exit 0
 
